### PR TITLE
add sep v1.0.0

### PR DESCRIPTION
**Pull request by kbarbary**
Not sure what the latest is on using conda-forge versus the openastronomy channel, but I thought I'd give this a try!

### CODE REVIEW

**Comment by mwcraig** [comment]
@kbarbary -- I'll need to make some CI setup changes; mind if I cherry-pick this to a separate PR? Really need to migrate most of this to conda-forge one of these days!

**Comment by kbarbary** [comment]
Sure, or just manually copy it if it's easier! I could also just submit this to conda-forge now if you want to start encouraging people to migrate.

**Comment by bsipocz** [comment]
@mwcraig - Could we follow here what we do in the astropy channel? Copy packages from `conda-forge` when they're available there, but keep the channel as a collection for astro/astropy related packages?

**Comment by mwcraig** [comment]
@bsipocz -- that is the intent. It would be nice to eventually move all of the building over to conda-forge now that copying (usually) works. This already copies sunpy, and maybe one other, from conda-forge to here.

**Comment by bsipocz** [comment]
Yes, we copy glue and a few package dependencies to `astropy`, too.

**Comment by astrofrog** [comment]
@mwcraig @bsipocz - just out of curiosity, how do you do the copying?

**Comment by Cadair** [comment]
also while we are on the topic, do you copy wcsaxes here? because otherwise sunpy wont install off just this channel.

**Comment by bsipocz** [comment]
@Cadair - wcsaxes as an affiliated package builds in `astropy` by default I think, but then everything from there is copied over here, too.

@astrofrog - My limited understanding is that a list of channels (conda-forge and astropy by default I think) are inspected, and if the package available there it gets copied over without building it, but it's @mwcraig who knows all the details

**Comment by mwcraig** [comment]
@astrofrog -- `conda-build-all` will copy packages from one of the `--inspect-channel`s to the `--destination-channel`. For anything listed in `requirements.yml` (which is what controls recipes are generated for the channel) the built package will be copied if it exists.

This brings up a weakness the current setup. For openastronomy to include everything in the astropy, the requirements here need, in principle, to include everything in the astropy channel's requirements, but that doubles the effort. 

I'll have some time Thursday morning to work on this a bit, have a couple ideas for simplification.

**Comment by astrofrog** [comment]
> This brings up a weakness the current setup. For openastronomy to include everything in the astropy, the requirements here need, in principle, to include everything in the astropy channel's requirements, but that doubles the effort.

I'm wondering if we really need both `astropy` and `openastronomy` channels? Don't we really just need one channel for astronomy packages? (Note that I have registered the 'astronomy' channel in case we ever want to use that...)

(Note that there is also astroconda, but that's not managed by us - however there's no reason why we couldn't copy hard-to-build packages like IRAF and others from there into our channel too)

**Comment by pllim** [comment]
We get so many help calls on IRAF not working this and that. Don't do it!

**Comment by Cadair** [comment]
it would be nice to have this channel be an astronomy specific subset of conda-forge, seeing how if you have conda-forge as your primary channel you get almost everything from there now (even Python and conda).

**Comment by astrofrog** [comment]
@Cadair - yes, personally I think it would be nice to do what you are suggesting - move the remaining packages that are still build here to conda-forge and then just mirror the minimal subset of packages needed. I do find it frustrating to end up with _everything_ conda-forge.

**Comment by mwcraig** [comment]
I think astroconda is really a different kettle of fish: it is a carefully constructed to support a successful IRAF install...

**Comment by mwcraig** [comment]
@Cadair @astrofrog -- it seems like the build/copy system should look something like this:
- Build is done on conda-forge (auto-generating the PRs to make that happen, or at least the recipes necessary, would be nice).
- A custom channel like this contains just a list of requirements (package name and perhaps version).
- A bot, independent of this specific channel, runs once a day to copy any packages in the requirements from conda-forge to here.

Thoughts?

**Comment by mwcraig** [comment]
@kbarbary -- I just merged #24, which builds sep. Closing this one...

**Pull request closed without merging**
