### PR TITLE
Add healpy

### PR DESCRIPTION
**Pull request by mwcraig**
@cdeil -- once this passes and is merged healpy will be available.

### CODE REVIEW

**Comment by cdeil** [comment]
This is an implementation of this feature request:
https://github.com/astropy/conda-builder-affiliated/issues/48

cc @woodmd

**Comment by lpsinger** [comment]
It's trying to install `nose`, which is a test-only dependency. Why not try what the error message says?

`Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml`

If you need it to run the Healpy unit tests, then try adding `nose` to `meta.yaml`.

**Comment by mwcraig** [comment]
What I don't understand is _why_ it is trying to install `nose`. It isn't required for `healpy` testing...in any event, I've added a recipe template for it that includes nose in the test environment and excluded Windows builds.

**Comment by lpsinger** [comment]
> What I don't understand is why it is trying to install nose. It isn't required for healpy testing...

Hmm. You're right, it only requires pytest. Odd.

**Comment by cdeil** [comment]
One of the dependencies in turn depends on nose?

(I think @mwcraig and I looked into this briefly at the PyAstro16 workshop and couldn't figure out where the nose dependency came from.)

**Comment by mwcraig** [comment]
The windows failure is unrelated to healpy (it is still trying to build sunpy on Windows). I fixed the `sunpy` problem with the latest push, so once we have green lights I'll merge and healpy with be available shortly after that.

**Comment by mwcraig** [comment]
The Windows skip is broken, but I'm merging this anyway. Failure noted at astropy/conda-build-tools#17

**Comment by mwcraig** [comment]
And....healpy is available! (on mac and linux)

**Pull request merged**
