### PR TITLE
Update MPDAF 2.1

### PR DESCRIPTION
**Pull request by saimn**

### CODE REVIEW

**Comment by saimn** [comment]
@mwcraig : I get this error, any idea why ?

> Package missing in current linux-64 channels: 
> - cfitsio

**Comment by saimn** [comment]
The openastronomy channel is no more present in the travis.yml file (it is in appveyor). Is it intentional ? I have added it to check that it builds.

**Comment by mwcraig** [comment]
@saimn -- thanks for catching the missing openastronomy. I've restarted the travis job that failed (due to an anaconda server error).

**Comment by saimn** [comment]
Thanks @mwcraig , it is all green now :)

**Comment by mwcraig** [comment]
Thanks again, merged!

**Comment by mwcraig** [comment]
@saimn -- just a heads up that the mac build seems to be failing now that I've merged. Looks like it is still an anaconda problem, will continue to restart until it succeeds...

**Comment by saimn** [comment]
Ok,thanks @mwcraig !

**Comment by mwcraig** [comment]
Incidentally, this has built (took a couple days but now down for all platforms).

**Pull request merged**
