### PR TITLE
build sunpy on windows

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by mwcraig** [comment]
@Cadair -- this needs to be fixed: astropy/conda-build-tools#17 (right now this build fails because the `exclude platform` for `healpy`, which can't be built on windows, is being built).

As a short-run fix, please delete healpy entirely from the requirements so we can see if sunpy itself builds or not.

**Comment by Cadair** [comment]
Don't know what happened to the python 3.5 build there..

**Comment by mwcraig** [comment]
Looks like it was glymur that failed because it couldn't find a DLL it needed...not sure what the fix is.

**Comment by Cadair** [comment]
why has that only come up now on that build?!

**Comment by mwcraig** [comment]
Welcome to the wonderful world of conda-build...

**Comment by mwcraig** [comment]
There was a change in how DLLs are bundled (or not) in python 3.5 on windows, so it doesn't surprise me too much. Can poke around later, hopefully....

**Comment by Cadair** [comment]
@mwcraig You got any ideas where I should start looking into this, we have a couple of SunPy releases coming up and I could really do with this working.

**Comment by mwcraig** [comment]
It was failing on hgtools....no idea why. Re-running that build to see what happens[1].

[1] Full disclosure: I accidently hit the restart button on the build.

**Comment by mwcraig** [comment]
and....success!

**Comment by Cadair** [comment]
this removes healpy...

**Comment by mwcraig** [comment]
Can get the fix in for healpy later today (classes done!!)

**Comment by Cadair** [comment]
merge this then?

**Comment by mwcraig** [comment]
hold off a couple hours, let's get healpy building.If you want, go ahead and add the healpy build back in, then I can restart the build (which will fail) once I think I've fixed things.

**Comment by mwcraig** [comment]
Testing a workaround to the latest conda-build bug (which is preventing uploads of the tool that generates the recipes).....

**Comment by mwcraig** [comment]
@Cadair -- if this passes feel free to merge.

**Pull request merged**
