### PR TITLE
Add recipe for fitsio

### PR DESCRIPTION
**Pull request by saimn**

### CODE REVIEW

**Comment by saimn** [comment]
From #17 :

> Give this about 15 minutes, then rebase the fitsio PR...

Just to clarify: fitsio does not require the cfitsio package (it bundles its own version). 
The build fail only on Windows, which [apparently](https://github.com/esheldon/fitsio/issues/47) is not supported, so I will exclude Windows.

**Comment by mwcraig** [comment]
@saimn -- this should be good to rebase now

**Comment by mwcraig** [comment]
Thanks, merging!

When I get some time I may port the recipes themselves over to conda-forge for building, but will make sure they remain available in the openastronomy channel. I've hit enough issues with conda-forge conflicts with defaults over the last month or so to want to stay away from recommending that as a channel for the end user.

**Comment by saimn** [comment]
Ok, thanks !

**Pull request merged**
